### PR TITLE
bump moc

### PR DESCRIPTION
**Pull request by chenyan-dfinity**
* bump moc
* bump dfx
* bump cdk
* update ledger did file

### CODE REVIEW

**Review by ggreif — APPROVED** [review]
LGTM!

The tests fail, though... But the `motoko-base` tests on `master` are fine, `textCompare` is present. So what is the problem here?

**Comment by chenyan-dfinity** [comment]
The problem is we are using `base` from `master`, but the `moc` in the latest dfx doesn't include `Prim.textCompare` yet

**Comment by ggreif** [comment]
> The problem is we are using `base` from `master`, but the `moc` in the latest dfx doesn't include `Prim.textCompare` yet

Ah, so  we have to wait for a new `dfx`, or is there an _envvar_ trick we can try?

**Comment by ggreif** [comment]
Maybe you can pin `motoko-base` 03513d76580b9e674519d0b1fc58b161d3c3f16d?

**Pull request merged**
