### PR TITLE
feat: store list of whitelisted wasms in a file, instead of hardcoding

### PR DESCRIPTION
**Pull request by smallstepman**
reference: https://github.com/dfinity/sdk/pull/3267#discussion_r1277915661

This change will allow us to extend the list of whitelisted wasms more easily because, (programmatically) it is much easier to append a line to a text file than edit the rust source code file.

### CODE REVIEW

**Review by sesi200 — APPROVED** [review]
Not a fan of the performance implications but it'll work well enough

**Comment by chenyan-dfinity** [comment]
I don't think we need build script. The trick is to use `include!` instead of `include_str!`.

In the text file, the format will be,
```
vec![
hash1, // dfx 0.14.0
hash2, // dfx 0.15.0
]
```
In `lib.rs`, we can use `let white_list = include!("white_list.txt");`.

The downside is that we cannot use const array, as that would require us to know the array length. But since the list is short, `vec!` works fine.

I will create a PR to fix the CI issue.

**Comment by chenyan-dfinity** [comment]
Can you sync with main and retry CI?

**Comment by smallstepman** [comment]
thanks @chenyan-dfinity, please take a second look

**Review by chenyan-dfinity — APPROVED** [review]

**Pull request merged**
