### PR TITLE
(fix) Make InputArgs fields consistent with rest of UI

### PR DESCRIPTION
**Pull request by taylorham**
## Before:
Screen Shot 2021-09-15 at 2 00 36 PM
## After:
Screen Shot 2021-09-28 at 1 24 56 PM

### CODE REVIEW

**Comment by taylorham** [comment]
Hey @chenyan-dfinity! I wasn't sure if you wanted more padding inside the InitArgs box or if it was only for the spacing between the bottom and the checkbox.

Let me know if this looks alright to you, and I can easily boost the inner padding if you'd like.

**Comment by chenyan-dfinity** [comment]
LGTM!

Is there a better border color for the InitContainer? The gray border feels a bit different from the rest of the UI.

**Comment by chenyan-dfinity** [comment]
Also the deploy modal can be wider, so that "This service requires the following installation arguments" can be in one line.

**Comment by taylorham** [comment]
## Updated:
Screen Shot 2021-09-28 at 4 12 57 PM

Let me know what you think, @chenyan-dfinity

**Comment by chenyan-dfinity** [comment]
Looks great! Did you push a new commit?

**Comment by taylorham** [comment]
Got ahead of myself. Ready now 😛

**Review by chenyan-dfinity — APPROVED** [review]

**Pull request merged**
